# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Mozhi systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mozhi_identifier }}.service"
  register: mozhi_service_stat

- name: Uninstall Mozhi systemd services and files
  when: mozhi_service_stat.stat.exists | bool
  block:
    - name: Ensure Mozhi systemd service is stopped
      ansible.builtin.service:
        name: "{{ mozhi_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Mozhi systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mozhi_identifier }}.service"
        state: absent

    - name: Ensure Mozhi container network does not exist
      when: mozhi_container_network_deletion_enabled
      block:
        - name: Ensure Mozhi container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ mozhi_container_network }}"
            state: absent
          register: mozhi_network_deletion_result

        - name: Ensure Mozhi container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ mozhi_container_network }}
          register: mozhi_network_deletion_result
          changed_when: mozhi_container_network in mozhi_network_deletion_result.stdout

    - name: Ensure Mozhi path does not exist
      ansible.builtin.file:
        path: "{{ mozhi_base_path }}"
        state: absent
